version: "3.8"

services:
    db:
        image: postgres:16
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "${POSTGRES_PORT}:${POSTGRES_PORT}"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    app:
        build: .
        volumes:
            - .:/app:cached
        container_name: next_app
        depends_on:
            - db
        ports:
            - "3000:3000"
        environment:
            NODE_ENV: development
            DATABASE_URL: ${DATABASE_URL}
        command:
            ["sh", "-c", "npx prisma db push --accept-data-loss && npm run dev"]

volumes:
    postgres_data:
